2025-09-08 18:55:04,589 - INFO - Starting upload service
2025-09-08 18:55:04,589 - INFO - Starting new upload cycle
2025-09-08 18:55:04,591 - INFO - Found 0 files in upload log
2025-09-08 18:55:04,592 - INFO - Found 6 image files to process
2025-09-08 18:55:04,593 - INFO - Attempt 1 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 18:55:25,677 - ERROR - Error during attempt 1 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D40B9AF950>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 18:55:35,678 - INFO - Attempt 2 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 18:56:40,005 - INFO - Starting upload service
2025-09-08 18:56:40,005 - INFO - Starting new upload cycle
2025-09-08 18:56:40,006 - INFO - Found 0 files in upload log
2025-09-08 18:56:40,007 - INFO - Found 7 image files to process
2025-09-08 18:56:40,008 - INFO - Attempt 1 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 18:57:01,076 - ERROR - Error during attempt 1 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000018D54ADF9E0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 18:57:11,078 - INFO - Attempt 2 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 18:58:53,620 - INFO - Starting upload service
2025-09-08 18:58:53,621 - INFO - Starting new upload cycle
2025-09-08 18:58:53,621 - INFO - Found 0 files in upload log
2025-09-08 18:58:53,621 - INFO - Found 7 image files to process
2025-09-08 18:58:53,621 - INFO - Attempt 1 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 18:59:14,708 - ERROR - Error during attempt 1 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC37BFE0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 18:59:24,709 - INFO - Attempt 2 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 18:59:45,728 - ERROR - Error during attempt 2 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC52FF80>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 18:59:55,729 - INFO - Attempt 3 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 19:00:16,785 - ERROR - Error during attempt 3 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC5685C0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:00:16,785 - ERROR - All upload attempts failed for OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 19:00:16,785 - WARNING - Failed to process OptiA1_17-15-16_2025-09-08_0x78.jpg after retries
2025-09-08 19:00:16,785 - INFO - Attempt 1 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 19:00:37,850 - ERROR - Error during attempt 1 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC52FE60>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:00:47,852 - INFO - Attempt 2 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 19:01:08,877 - ERROR - Error during attempt 2 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC568530>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:01:18,878 - INFO - Attempt 3 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 19:01:39,922 - ERROR - Error during attempt 3 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC568B90>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:01:39,922 - ERROR - All upload attempts failed for OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 19:01:39,922 - WARNING - Failed to process OptiA1_17-25-20_2025-09-08_0x56.jpg after retries
2025-09-08 19:01:39,922 - INFO - Attempt 1 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 19:02:00,996 - ERROR - Error during attempt 1 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC569220>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:02:10,998 - INFO - Attempt 2 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 19:02:32,061 - ERROR - Error during attempt 2 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC5698E0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:02:42,062 - INFO - Attempt 3 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 19:03:03,123 - ERROR - Error during attempt 3 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC56A030>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:03:03,123 - ERROR - All upload attempts failed for OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 19:03:03,123 - WARNING - Failed to process OptiA1_17-27-38_2025-09-08_0x32.jpg after retries
2025-09-08 19:03:03,123 - INFO - Attempt 1 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 19:03:24,171 - ERROR - Error during attempt 1 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC171760>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:03:34,173 - INFO - Attempt 2 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 19:03:55,219 - ERROR - Error during attempt 2 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC52FC80>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:04:05,220 - INFO - Attempt 3 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 19:04:26,264 - ERROR - Error during attempt 3 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC56A5D0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:04:26,264 - ERROR - All upload attempts failed for OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 19:04:26,264 - WARNING - Failed to process OptiA1_18-24-58_2025-08-25_0x92.jpg after retries
2025-09-08 19:04:26,264 - INFO - Attempt 1 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 19:04:47,309 - ERROR - Error during attempt 1 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC569A90>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:04:57,309 - INFO - Attempt 2 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 19:05:18,362 - ERROR - Error during attempt 2 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC568FE0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:05:28,363 - INFO - Attempt 3 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 19:05:49,415 - ERROR - Error during attempt 3 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC568800>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:05:49,415 - ERROR - All upload attempts failed for OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 19:05:49,415 - WARNING - Failed to process OptiA1_18-25-35_2025-08-25_0x83.jpg after retries
2025-09-08 19:05:49,415 - INFO - Attempt 1 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 19:06:10,467 - ERROR - Error during attempt 1 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC5685F0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:06:20,469 - INFO - Attempt 2 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 19:06:41,532 - ERROR - Error during attempt 2 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC56AAB0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:06:51,533 - INFO - Attempt 3 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 19:07:12,559 - ERROR - Error during attempt 3 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC52FE60>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:07:12,559 - ERROR - All upload attempts failed for OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 19:07:12,559 - WARNING - Failed to process OptiA1_18-26-24_2025-08-25_0x46.jpg after retries
2025-09-08 19:07:12,559 - INFO - Attempt 1 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 19:07:33,609 - ERROR - Error during attempt 1 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC52F200>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:07:43,610 - INFO - Attempt 2 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 19:08:04,651 - ERROR - Error during attempt 2 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC56A8A0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:08:14,653 - INFO - Attempt 3 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 19:08:35,712 - ERROR - Error during attempt 3 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D4FC568530>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:08:35,712 - ERROR - All upload attempts failed for OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 19:08:35,713 - WARNING - Failed to process OptiA1_18-55-10_2025-09-08_0x43.jpg after retries
2025-09-08 19:08:35,713 - INFO - Upload cycle completed. Waiting 600 seconds
2025-09-08 19:14:36,892 - INFO - Upload service stopped by user
2025-09-08 19:16:05,394 - INFO - Starting upload service
2025-09-08 19:16:05,394 - INFO - Starting new upload cycle
2025-09-08 19:16:05,394 - INFO - Found 0 files in upload log
2025-09-08 19:16:05,395 - INFO - Found 7 image files to process
2025-09-08 19:16:05,395 - INFO - Attempt 1 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 19:16:26,450 - ERROR - Error during attempt 1 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001435C9BFA70>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:16:36,451 - INFO - Attempt 2 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 19:16:57,482 - ERROR - Error during attempt 2 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001435C9F80B0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:17:07,483 - INFO - Attempt 3 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 19:20:41,596 - INFO - Starting upload service
2025-09-08 19:20:41,596 - INFO - Starting new upload cycle
2025-09-08 19:20:41,597 - INFO - Found 0 files in upload log
2025-09-08 19:20:41,598 - INFO - Found 8 image files to process
2025-09-08 19:20:41,598 - INFO - Attempt 1 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 19:21:02,678 - ERROR - Error during attempt 1 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70740>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:21:02,678 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:21:12,680 - INFO - Attempt 2 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 19:21:33,724 - ERROR - Error during attempt 2 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70BF0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:21:33,725 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:21:43,725 - INFO - Attempt 3 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 19:22:04,778 - ERROR - Error during attempt 3 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71190>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:22:04,779 - ERROR - All upload attempts failed for OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 19:22:04,779 - WARNING - Failed to process OptiA1_17-15-16_2025-09-08_0x78.jpg after retries
2025-09-08 19:22:04,779 - INFO - Attempt 1 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 19:22:25,829 - ERROR - Error during attempt 1 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71160>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:22:25,829 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:22:35,831 - INFO - Attempt 2 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 19:22:56,880 - ERROR - Error during attempt 2 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70050>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:22:56,880 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:23:06,881 - INFO - Attempt 3 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 19:23:27,927 - ERROR - Error during attempt 3 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71850>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:23:27,927 - ERROR - All upload attempts failed for OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 19:23:27,927 - WARNING - Failed to process OptiA1_17-25-20_2025-09-08_0x56.jpg after retries
2025-09-08 19:23:27,929 - INFO - Attempt 1 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 19:23:48,991 - ERROR - Error during attempt 1 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71EE0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:23:48,991 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:23:58,991 - INFO - Attempt 2 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 19:24:20,046 - ERROR - Error during attempt 2 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA725A0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:24:20,046 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:24:30,047 - INFO - Attempt 3 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 19:24:51,106 - ERROR - Error during attempt 3 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72CF0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:24:51,106 - ERROR - All upload attempts failed for OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 19:24:51,106 - WARNING - Failed to process OptiA1_17-27-38_2025-09-08_0x32.jpg after retries
2025-09-08 19:24:51,106 - INFO - Attempt 1 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 19:25:12,162 - ERROR - Error during attempt 1 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA0BB60>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:25:12,162 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:25:22,164 - INFO - Attempt 2 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 19:25:43,201 - ERROR - Error during attempt 2 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA732F0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:25:43,201 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:25:53,201 - INFO - Attempt 3 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 19:26:14,265 - ERROR - Error during attempt 3 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72720>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:26:14,265 - ERROR - All upload attempts failed for OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 19:26:14,265 - WARNING - Failed to process OptiA1_18-24-58_2025-08-25_0x92.jpg after retries
2025-09-08 19:26:14,266 - INFO - Attempt 1 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 19:26:35,340 - ERROR - Error during attempt 1 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72120>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:26:35,340 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:26:45,342 - INFO - Attempt 2 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 19:27:06,377 - ERROR - Error during attempt 2 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA717C0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:27:06,377 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:27:16,379 - INFO - Attempt 3 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 19:27:37,420 - ERROR - Error during attempt 3 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70BF0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:27:37,420 - ERROR - All upload attempts failed for OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 19:27:37,420 - WARNING - Failed to process OptiA1_18-25-35_2025-08-25_0x83.jpg after retries
2025-09-08 19:27:37,420 - INFO - Attempt 1 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 19:27:58,475 - ERROR - Error during attempt 1 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA711C0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:27:58,476 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:28:08,477 - INFO - Attempt 2 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 19:28:29,515 - ERROR - Error during attempt 2 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73770>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:28:29,515 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:28:39,517 - INFO - Attempt 3 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 19:29:00,571 - ERROR - Error during attempt 3 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4F7B4F80>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:29:00,571 - ERROR - All upload attempts failed for OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 19:29:00,572 - WARNING - Failed to process OptiA1_18-26-24_2025-08-25_0x46.jpg after retries
2025-09-08 19:29:00,572 - INFO - Attempt 1 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 19:29:21,624 - ERROR - Error during attempt 1 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA737A0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:29:21,624 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:29:31,625 - INFO - Attempt 2 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 19:29:52,676 - ERROR - Error during attempt 2 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70F50>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:29:52,677 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:30:02,677 - INFO - Attempt 3 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 19:30:23,753 - ERROR - Error during attempt 3 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70F80>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:30:23,753 - ERROR - All upload attempts failed for OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 19:30:23,753 - WARNING - Failed to process OptiA1_18-55-10_2025-09-08_0x43.jpg after retries
2025-09-08 19:30:23,754 - INFO - Attempt 1 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 19:30:44,822 - ERROR - Error during attempt 1 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA716A0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:30:44,822 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:30:54,823 - INFO - Attempt 2 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 19:31:15,867 - ERROR - Error during attempt 2 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72090>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:31:15,868 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:31:25,869 - INFO - Attempt 3 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 19:31:46,899 - ERROR - Error during attempt 3 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA726C0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:31:46,899 - ERROR - All upload attempts failed for OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 19:31:46,899 - WARNING - Failed to process OptiA1_19-16-36_2025-09-08_0x74.jpg after retries
2025-09-08 19:31:46,899 - INFO - Upload cycle completed. Waiting 600 seconds
2025-09-08 19:41:46,901 - INFO - Starting new upload cycle
2025-09-08 19:41:46,903 - INFO - Found 0 files in upload log
2025-09-08 19:41:46,904 - INFO - Found 8 image files to process
2025-09-08 19:41:46,904 - INFO - Attempt 1 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 19:42:07,969 - ERROR - Error during attempt 1 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA0BB60>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:42:07,969 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:42:17,970 - INFO - Attempt 2 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 19:42:39,026 - ERROR - Error during attempt 2 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72DB0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:42:39,026 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:42:49,026 - INFO - Attempt 3 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 19:43:10,067 - ERROR - Error during attempt 3 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72180>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:43:10,067 - ERROR - All upload attempts failed for OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 19:43:10,067 - WARNING - Failed to process OptiA1_17-15-16_2025-09-08_0x78.jpg after retries
2025-09-08 19:43:10,067 - INFO - Attempt 1 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 19:43:31,115 - ERROR - Error during attempt 1 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71D00>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:43:31,115 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:43:41,115 - INFO - Attempt 2 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 19:44:02,165 - ERROR - Error during attempt 2 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA713A0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:44:02,165 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:44:12,167 - INFO - Attempt 3 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 19:44:33,223 - ERROR - Error during attempt 3 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70EF0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:44:33,224 - ERROR - All upload attempts failed for OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 19:44:33,224 - WARNING - Failed to process OptiA1_17-25-20_2025-09-08_0x56.jpg after retries
2025-09-08 19:44:33,224 - INFO - Attempt 1 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 19:44:54,285 - ERROR - Error during attempt 1 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73380>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:44:54,285 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:45:04,286 - INFO - Attempt 2 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 19:45:25,350 - ERROR - Error during attempt 2 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72FF0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:45:25,350 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:45:35,351 - INFO - Attempt 3 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 19:45:56,402 - ERROR - Error during attempt 3 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4F7B4F80>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:45:56,402 - ERROR - All upload attempts failed for OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 19:45:56,404 - WARNING - Failed to process OptiA1_17-27-38_2025-09-08_0x32.jpg after retries
2025-09-08 19:45:56,404 - INFO - Attempt 1 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 19:46:17,438 - ERROR - Error during attempt 1 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA738F0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:46:17,438 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:46:27,439 - INFO - Attempt 2 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 19:46:48,470 - ERROR - Error during attempt 2 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71220>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:46:48,470 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:46:58,471 - INFO - Attempt 3 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 19:47:19,531 - ERROR - Error during attempt 3 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70770>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:47:19,531 - ERROR - All upload attempts failed for OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 19:47:19,531 - WARNING - Failed to process OptiA1_18-24-58_2025-08-25_0x92.jpg after retries
2025-09-08 19:47:19,531 - INFO - Attempt 1 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 19:47:40,598 - ERROR - Error during attempt 1 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71CA0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:47:40,598 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:47:50,598 - INFO - Attempt 2 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 19:48:11,645 - ERROR - Error during attempt 2 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA728D0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:48:11,645 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:48:21,646 - INFO - Attempt 3 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 19:48:42,710 - ERROR - Error during attempt 3 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA721E0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:48:42,710 - ERROR - All upload attempts failed for OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 19:48:42,710 - WARNING - Failed to process OptiA1_18-25-35_2025-08-25_0x83.jpg after retries
2025-09-08 19:48:42,712 - INFO - Attempt 1 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 19:49:03,763 - ERROR - Error during attempt 1 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72930>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:49:03,763 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:49:13,764 - INFO - Attempt 2 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 19:49:34,822 - ERROR - Error during attempt 2 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4F9AF860>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:49:34,822 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:49:44,824 - INFO - Attempt 3 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 19:50:05,859 - ERROR - Error during attempt 3 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72360>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:50:05,860 - ERROR - All upload attempts failed for OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 19:50:05,860 - WARNING - Failed to process OptiA1_18-26-24_2025-08-25_0x46.jpg after retries
2025-09-08 19:50:05,860 - INFO - Attempt 1 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 19:50:26,893 - ERROR - Error during attempt 1 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71970>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:50:26,893 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:50:36,895 - INFO - Attempt 2 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 19:50:57,931 - ERROR - Error during attempt 2 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71490>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:50:57,931 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:51:07,932 - INFO - Attempt 3 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 19:51:28,975 - ERROR - Error during attempt 3 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70EC0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:51:28,975 - ERROR - All upload attempts failed for OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 19:51:28,975 - WARNING - Failed to process OptiA1_18-55-10_2025-09-08_0x43.jpg after retries
2025-09-08 19:51:28,975 - INFO - Attempt 1 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 19:51:50,018 - ERROR - Error during attempt 1 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73830>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:51:50,019 - INFO - Waiting 10 seconds before retry 2
2025-09-08 19:52:00,019 - INFO - Attempt 2 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 19:52:21,061 - ERROR - Error during attempt 2 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73410>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:52:21,061 - INFO - Waiting 10 seconds before retry 3
2025-09-08 19:52:31,062 - INFO - Attempt 3 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 19:52:52,124 - ERROR - Error during attempt 3 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4F9AF740>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 19:52:52,124 - ERROR - All upload attempts failed for OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 19:52:52,126 - WARNING - Failed to process OptiA1_19-16-36_2025-09-08_0x74.jpg after retries
2025-09-08 19:52:52,126 - INFO - Upload cycle completed. Waiting 600 seconds
2025-09-08 20:02:52,126 - INFO - Starting new upload cycle
2025-09-08 20:02:52,127 - INFO - Found 0 files in upload log
2025-09-08 20:02:52,127 - INFO - Found 8 image files to process
2025-09-08 20:02:52,128 - INFO - Attempt 1 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 20:03:13,177 - ERROR - Error during attempt 1 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA735C0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:03:13,177 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:03:23,178 - INFO - Attempt 2 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 20:03:44,245 - ERROR - Error during attempt 2 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70C80>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:03:44,245 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:03:54,246 - INFO - Attempt 3 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 20:04:15,301 - ERROR - Error during attempt 3 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70E60>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:04:15,301 - ERROR - All upload attempts failed for OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 20:04:15,301 - WARNING - Failed to process OptiA1_17-15-16_2025-09-08_0x78.jpg after retries
2025-09-08 20:04:15,301 - INFO - Attempt 1 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 20:04:36,348 - ERROR - Error during attempt 1 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71D60>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:04:36,349 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:04:46,350 - INFO - Attempt 2 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 20:05:07,384 - ERROR - Error during attempt 2 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71D30>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:05:07,385 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:05:17,385 - INFO - Attempt 3 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 20:05:38,435 - ERROR - Error during attempt 3 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72360>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:05:38,436 - ERROR - All upload attempts failed for OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 20:05:38,436 - WARNING - Failed to process OptiA1_17-25-20_2025-09-08_0x56.jpg after retries
2025-09-08 20:05:38,436 - INFO - Attempt 1 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 20:05:59,479 - ERROR - Error during attempt 1 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA3BB30>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:05:59,479 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:06:09,480 - INFO - Attempt 2 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 20:06:30,507 - ERROR - Error during attempt 2 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73E60>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:06:30,507 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:06:40,508 - INFO - Attempt 3 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 20:07:01,565 - ERROR - Error during attempt 3 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72060>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:07:01,566 - ERROR - All upload attempts failed for OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 20:07:01,566 - WARNING - Failed to process OptiA1_17-27-38_2025-09-08_0x32.jpg after retries
2025-09-08 20:07:01,566 - INFO - Attempt 1 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 20:07:22,612 - ERROR - Error during attempt 1 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71A00>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:07:22,612 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:07:32,614 - INFO - Attempt 2 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 20:07:53,656 - ERROR - Error during attempt 2 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70110>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:07:53,656 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:08:03,657 - INFO - Attempt 3 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 20:08:24,707 - ERROR - Error during attempt 3 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70CB0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:08:24,707 - ERROR - All upload attempts failed for OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 20:08:24,707 - WARNING - Failed to process OptiA1_18-24-58_2025-08-25_0x92.jpg after retries
2025-09-08 20:08:24,707 - INFO - Attempt 1 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 20:08:45,772 - ERROR - Error during attempt 1 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70E90>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:08:45,772 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:08:55,774 - INFO - Attempt 2 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 20:09:16,839 - ERROR - Error during attempt 2 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D505D0050>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:09:16,839 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:09:26,840 - INFO - Attempt 3 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 20:09:47,881 - ERROR - Error during attempt 3 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA730B0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:09:47,882 - ERROR - All upload attempts failed for OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 20:09:47,882 - WARNING - Failed to process OptiA1_18-25-35_2025-08-25_0x83.jpg after retries
2025-09-08 20:09:47,882 - INFO - Attempt 1 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 20:10:08,935 - ERROR - Error during attempt 1 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70AA0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:10:08,935 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:10:18,936 - INFO - Attempt 2 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 20:10:39,997 - ERROR - Error during attempt 2 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA712E0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:10:39,997 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:10:49,998 - INFO - Attempt 3 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 20:11:11,030 - ERROR - Error during attempt 3 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71AF0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:11:11,031 - ERROR - All upload attempts failed for OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 20:11:11,031 - WARNING - Failed to process OptiA1_18-26-24_2025-08-25_0x46.jpg after retries
2025-09-08 20:11:11,031 - INFO - Attempt 1 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 20:11:32,086 - ERROR - Error during attempt 1 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71C40>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:11:32,086 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:11:42,088 - INFO - Attempt 2 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 20:12:03,112 - ERROR - Error during attempt 2 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72330>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:12:03,113 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:12:13,113 - INFO - Attempt 3 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 20:12:34,160 - ERROR - Error during attempt 3 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4F8EE660>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:12:34,161 - ERROR - All upload attempts failed for OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 20:12:34,161 - WARNING - Failed to process OptiA1_18-55-10_2025-09-08_0x43.jpg after retries
2025-09-08 20:12:34,161 - INFO - Attempt 1 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 20:12:55,197 - ERROR - Error during attempt 1 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72960>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:12:55,197 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:13:05,197 - INFO - Attempt 2 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 20:13:26,244 - ERROR - Error during attempt 2 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71BE0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:13:26,244 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:13:36,246 - INFO - Attempt 3 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 20:13:57,318 - ERROR - Error during attempt 3 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71940>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:13:57,326 - ERROR - All upload attempts failed for OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 20:13:57,326 - WARNING - Failed to process OptiA1_19-16-36_2025-09-08_0x74.jpg after retries
2025-09-08 20:13:57,326 - INFO - Upload cycle completed. Waiting 600 seconds
2025-09-08 20:23:57,327 - INFO - Starting new upload cycle
2025-09-08 20:23:57,328 - INFO - Found 0 files in upload log
2025-09-08 20:23:57,328 - INFO - Found 8 image files to process
2025-09-08 20:23:57,328 - INFO - Attempt 1 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 20:24:18,366 - ERROR - Error during attempt 1 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71880>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:24:18,366 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:24:28,368 - INFO - Attempt 2 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 20:24:49,421 - ERROR - Error during attempt 2 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70E30>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:24:49,421 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:24:59,423 - INFO - Attempt 3 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 20:25:20,481 - ERROR - Error during attempt 3 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71010>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:25:20,482 - ERROR - All upload attempts failed for OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 20:25:20,482 - WARNING - Failed to process OptiA1_17-15-16_2025-09-08_0x78.jpg after retries
2025-09-08 20:25:20,482 - INFO - Attempt 1 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 20:25:41,520 - ERROR - Error during attempt 1 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4F9AF860>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:25:41,522 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:25:51,522 - INFO - Attempt 2 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 20:26:12,582 - ERROR - Error during attempt 2 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4F8BB470>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:26:12,582 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:26:22,583 - INFO - Attempt 3 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 20:26:43,646 - ERROR - Error during attempt 3 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA733B0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:26:43,646 - ERROR - All upload attempts failed for OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 20:26:43,646 - WARNING - Failed to process OptiA1_17-25-20_2025-09-08_0x56.jpg after retries
2025-09-08 20:26:43,646 - INFO - Attempt 1 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 20:27:04,689 - ERROR - Error during attempt 1 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA712E0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:27:04,689 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:27:14,689 - INFO - Attempt 2 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 20:27:35,743 - ERROR - Error during attempt 2 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71AF0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:27:35,743 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:27:45,745 - INFO - Attempt 3 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 20:28:06,805 - ERROR - Error during attempt 3 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71C40>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:28:06,805 - ERROR - All upload attempts failed for OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 20:28:06,806 - WARNING - Failed to process OptiA1_17-27-38_2025-09-08_0x32.jpg after retries
2025-09-08 20:28:06,806 - INFO - Attempt 1 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 20:28:27,856 - ERROR - Error during attempt 1 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70B00>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:28:27,857 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:28:37,858 - INFO - Attempt 2 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 20:28:58,885 - ERROR - Error during attempt 2 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA3BD40>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:28:58,885 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:29:08,886 - INFO - Attempt 3 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 20:29:29,937 - ERROR - Error during attempt 3 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D505D07D0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:29:29,937 - ERROR - All upload attempts failed for OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 20:29:29,937 - WARNING - Failed to process OptiA1_18-24-58_2025-08-25_0x92.jpg after retries
2025-09-08 20:29:29,937 - INFO - Attempt 1 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 20:29:50,998 - ERROR - Error during attempt 1 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73CB0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:29:50,998 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:30:00,999 - INFO - Attempt 2 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 20:30:22,037 - ERROR - Error during attempt 2 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71DC0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:30:22,037 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:30:32,039 - INFO - Attempt 3 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 20:30:53,087 - ERROR - Error during attempt 3 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70FE0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:30:53,087 - ERROR - All upload attempts failed for OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 20:30:53,088 - WARNING - Failed to process OptiA1_18-25-35_2025-08-25_0x83.jpg after retries
2025-09-08 20:30:53,088 - INFO - Attempt 1 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 20:31:14,132 - ERROR - Error during attempt 1 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72FC0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:31:14,132 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:31:24,134 - INFO - Attempt 2 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 20:31:45,194 - ERROR - Error during attempt 2 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70F80>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:31:45,194 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:31:55,196 - INFO - Attempt 3 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 20:32:16,249 - ERROR - Error during attempt 3 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA736B0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:32:16,249 - ERROR - All upload attempts failed for OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 20:32:16,249 - WARNING - Failed to process OptiA1_18-26-24_2025-08-25_0x46.jpg after retries
2025-09-08 20:32:16,249 - INFO - Attempt 1 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 20:32:37,320 - ERROR - Error during attempt 1 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4F9AF5C0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:32:37,321 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:32:47,322 - INFO - Attempt 2 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 20:33:08,382 - ERROR - Error during attempt 2 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D505D0200>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:33:08,383 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:33:18,384 - INFO - Attempt 3 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 20:33:39,426 - ERROR - Error during attempt 3 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71010>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:33:39,427 - ERROR - All upload attempts failed for OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 20:33:39,427 - WARNING - Failed to process OptiA1_18-55-10_2025-09-08_0x43.jpg after retries
2025-09-08 20:33:39,427 - INFO - Attempt 1 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 20:34:00,482 - ERROR - Error during attempt 1 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70E30>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:34:00,482 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:34:10,484 - INFO - Attempt 2 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 20:34:31,520 - ERROR - Error during attempt 2 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71880>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:34:31,520 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:34:41,521 - INFO - Attempt 3 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 20:35:02,562 - ERROR - Error during attempt 3 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71940>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:35:02,562 - ERROR - All upload attempts failed for OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 20:35:02,562 - WARNING - Failed to process OptiA1_19-16-36_2025-09-08_0x74.jpg after retries
2025-09-08 20:35:02,562 - INFO - Upload cycle completed. Waiting 600 seconds
2025-09-08 20:45:02,564 - INFO - Starting new upload cycle
2025-09-08 20:45:02,565 - INFO - Found 0 files in upload log
2025-09-08 20:45:02,565 - INFO - Found 8 image files to process
2025-09-08 20:45:02,565 - INFO - Attempt 1 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 20:45:23,626 - ERROR - Error during attempt 1 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72960>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:45:23,626 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:45:33,626 - INFO - Attempt 2 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 20:45:54,685 - ERROR - Error during attempt 2 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA093D0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:45:54,685 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:46:04,686 - INFO - Attempt 3 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 20:46:25,750 - ERROR - Error during attempt 3 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D505D06B0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:46:25,750 - ERROR - All upload attempts failed for OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 20:46:25,750 - WARNING - Failed to process OptiA1_17-15-16_2025-09-08_0x78.jpg after retries
2025-09-08 20:46:25,751 - INFO - Attempt 1 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 20:46:46,811 - ERROR - Error during attempt 1 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70B00>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:46:46,811 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:46:56,813 - INFO - Attempt 2 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 20:47:17,866 - ERROR - Error during attempt 2 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73DD0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:47:17,866 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:47:27,867 - INFO - Attempt 3 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 20:47:48,931 - ERROR - Error during attempt 3 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72420>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:47:48,931 - ERROR - All upload attempts failed for OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 20:47:48,931 - WARNING - Failed to process OptiA1_17-25-20_2025-09-08_0x56.jpg after retries
2025-09-08 20:47:48,931 - INFO - Attempt 1 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 20:48:09,973 - ERROR - Error during attempt 1 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71E50>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:48:09,974 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:48:19,975 - INFO - Attempt 2 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 20:48:41,032 - ERROR - Error during attempt 2 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71B80>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:48:41,032 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:48:51,035 - INFO - Attempt 3 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 20:49:12,097 - ERROR - Error during attempt 3 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73BC0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:49:12,097 - ERROR - All upload attempts failed for OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 20:49:12,098 - WARNING - Failed to process OptiA1_17-27-38_2025-09-08_0x32.jpg after retries
2025-09-08 20:49:12,098 - INFO - Attempt 1 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 20:49:33,171 - ERROR - Error during attempt 1 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72C00>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:49:33,171 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:49:43,173 - INFO - Attempt 2 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 20:50:04,221 - ERROR - Error during attempt 2 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4F9AF800>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:50:04,221 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:50:14,222 - INFO - Attempt 3 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 20:50:35,252 - ERROR - Error during attempt 3 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72F60>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:50:35,253 - ERROR - All upload attempts failed for OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 20:50:35,253 - WARNING - Failed to process OptiA1_18-24-58_2025-08-25_0x92.jpg after retries
2025-09-08 20:50:35,253 - INFO - Attempt 1 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 20:50:56,290 - ERROR - Error during attempt 1 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72570>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:50:56,290 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:51:06,292 - INFO - Attempt 2 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 20:51:27,362 - ERROR - Error during attempt 2 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA733B0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:51:27,362 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:51:37,363 - INFO - Attempt 3 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 20:51:58,434 - ERROR - Error during attempt 3 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70C50>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:51:58,434 - ERROR - All upload attempts failed for OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 20:51:58,434 - WARNING - Failed to process OptiA1_18-25-35_2025-08-25_0x83.jpg after retries
2025-09-08 20:51:58,434 - INFO - Attempt 1 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 20:52:19,477 - ERROR - Error during attempt 1 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70800>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:52:19,477 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:52:29,479 - INFO - Attempt 2 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 20:52:50,505 - ERROR - Error during attempt 2 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72300>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:52:50,505 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:53:00,506 - INFO - Attempt 3 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 20:53:21,539 - ERROR - Error during attempt 3 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72510>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:53:21,539 - ERROR - All upload attempts failed for OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 20:53:21,539 - WARNING - Failed to process OptiA1_18-26-24_2025-08-25_0x46.jpg after retries
2025-09-08 20:53:21,539 - INFO - Attempt 1 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 20:53:42,578 - ERROR - Error during attempt 1 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72A50>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:53:42,578 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:53:52,579 - INFO - Attempt 2 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 20:54:13,627 - ERROR - Error during attempt 2 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA717F0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:54:13,628 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:54:23,629 - INFO - Attempt 3 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 20:54:44,652 - ERROR - Error during attempt 3 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72180>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:54:44,652 - ERROR - All upload attempts failed for OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 20:54:44,652 - WARNING - Failed to process OptiA1_18-55-10_2025-09-08_0x43.jpg after retries
2025-09-08 20:54:44,652 - INFO - Attempt 1 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 20:55:05,697 - ERROR - Error during attempt 1 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70C20>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:55:05,697 - INFO - Waiting 10 seconds before retry 2
2025-09-08 20:55:15,698 - INFO - Attempt 2 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 20:55:36,742 - ERROR - Error during attempt 2 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71130>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:55:36,742 - INFO - Waiting 10 seconds before retry 3
2025-09-08 20:55:46,744 - INFO - Attempt 3 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 20:56:07,789 - ERROR - Error during attempt 3 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA732F0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 20:56:07,789 - ERROR - All upload attempts failed for OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 20:56:07,789 - WARNING - Failed to process OptiA1_19-16-36_2025-09-08_0x74.jpg after retries
2025-09-08 20:56:07,789 - INFO - Upload cycle completed. Waiting 600 seconds
2025-09-08 21:06:07,790 - INFO - Starting new upload cycle
2025-09-08 21:06:07,797 - INFO - Found 0 files in upload log
2025-09-08 21:06:07,797 - INFO - Found 8 image files to process
2025-09-08 21:06:07,797 - INFO - Attempt 1 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 21:06:28,865 - ERROR - Error during attempt 1 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73170>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:06:28,866 - INFO - Waiting 10 seconds before retry 2
2025-09-08 21:06:38,866 - INFO - Attempt 2 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 21:06:59,927 - ERROR - Error during attempt 2 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73980>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:06:59,927 - INFO - Waiting 10 seconds before retry 3
2025-09-08 21:07:09,928 - INFO - Attempt 3 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 21:07:30,984 - ERROR - Error during attempt 3 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70110>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:07:30,984 - ERROR - All upload attempts failed for OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 21:07:30,984 - WARNING - Failed to process OptiA1_17-15-16_2025-09-08_0x78.jpg after retries
2025-09-08 21:07:30,984 - INFO - Attempt 1 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 21:07:52,033 - ERROR - Error during attempt 1 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA728D0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:07:52,033 - INFO - Waiting 10 seconds before retry 2
2025-09-08 21:08:02,034 - INFO - Attempt 2 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 21:08:23,098 - ERROR - Error during attempt 2 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72600>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:08:23,098 - INFO - Waiting 10 seconds before retry 3
2025-09-08 21:08:33,099 - INFO - Attempt 3 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 21:08:54,143 - ERROR - Error during attempt 3 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73E30>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:08:54,143 - ERROR - All upload attempts failed for OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 21:08:54,143 - WARNING - Failed to process OptiA1_17-25-20_2025-09-08_0x56.jpg after retries
2025-09-08 21:08:54,143 - INFO - Attempt 1 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 21:09:15,181 - ERROR - Error during attempt 1 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72A50>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:09:15,181 - INFO - Waiting 10 seconds before retry 2
2025-09-08 21:09:25,182 - INFO - Attempt 2 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 21:09:46,229 - ERROR - Error during attempt 2 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D505D0260>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:09:46,230 - INFO - Waiting 10 seconds before retry 3
2025-09-08 21:09:56,231 - INFO - Attempt 3 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 21:10:17,288 - ERROR - Error during attempt 3 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA732C0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:10:17,288 - ERROR - All upload attempts failed for OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 21:10:17,289 - WARNING - Failed to process OptiA1_17-27-38_2025-09-08_0x32.jpg after retries
2025-09-08 21:10:17,289 - INFO - Attempt 1 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 21:10:38,362 - ERROR - Error during attempt 1 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA700B0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:10:38,362 - INFO - Waiting 10 seconds before retry 2
2025-09-08 21:10:48,362 - INFO - Attempt 2 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 21:11:09,401 - ERROR - Error during attempt 2 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72E10>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:11:09,402 - INFO - Waiting 10 seconds before retry 3
2025-09-08 21:11:19,403 - INFO - Attempt 3 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 21:11:40,459 - ERROR - Error during attempt 3 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73620>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:11:40,460 - ERROR - All upload attempts failed for OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 21:11:40,460 - WARNING - Failed to process OptiA1_18-24-58_2025-08-25_0x92.jpg after retries
2025-09-08 21:11:40,460 - INFO - Attempt 1 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 21:12:01,521 - ERROR - Error during attempt 1 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70E00>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:12:01,521 - INFO - Waiting 10 seconds before retry 2
2025-09-08 21:12:11,523 - INFO - Attempt 2 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 21:12:32,563 - ERROR - Error during attempt 2 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73AD0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:12:32,563 - INFO - Waiting 10 seconds before retry 3
2025-09-08 21:12:42,564 - INFO - Attempt 3 for file: OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 21:13:03,615 - ERROR - Error during attempt 3 for OptiA1_18-25-35_2025-08-25_0x83.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D505D0A40>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:13:03,615 - ERROR - All upload attempts failed for OptiA1_18-25-35_2025-08-25_0x83.jpg
2025-09-08 21:13:03,615 - WARNING - Failed to process OptiA1_18-25-35_2025-08-25_0x83.jpg after retries
2025-09-08 21:13:03,615 - INFO - Attempt 1 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 21:13:24,655 - ERROR - Error during attempt 1 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D505D0EF0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:13:24,655 - INFO - Waiting 10 seconds before retry 2
2025-09-08 21:13:34,656 - INFO - Attempt 2 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 21:13:55,696 - ERROR - Error during attempt 2 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72FF0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:13:55,696 - INFO - Waiting 10 seconds before retry 3
2025-09-08 21:14:05,697 - INFO - Attempt 3 for file: OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 21:14:26,763 - ERROR - Error during attempt 3 for OptiA1_18-26-24_2025-08-25_0x46.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA728D0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:14:26,763 - ERROR - All upload attempts failed for OptiA1_18-26-24_2025-08-25_0x46.jpg
2025-09-08 21:14:26,763 - WARNING - Failed to process OptiA1_18-26-24_2025-08-25_0x46.jpg after retries
2025-09-08 21:14:26,763 - INFO - Attempt 1 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 21:14:47,822 - ERROR - Error during attempt 1 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72600>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:14:47,822 - INFO - Waiting 10 seconds before retry 2
2025-09-08 21:14:57,823 - INFO - Attempt 2 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 21:15:18,865 - ERROR - Error during attempt 2 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73E30>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:15:18,865 - INFO - Waiting 10 seconds before retry 3
2025-09-08 21:15:28,866 - INFO - Attempt 3 for file: OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 21:15:49,907 - ERROR - Error during attempt 3 for OptiA1_18-55-10_2025-09-08_0x43.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72A50>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:15:49,909 - ERROR - All upload attempts failed for OptiA1_18-55-10_2025-09-08_0x43.jpg
2025-09-08 21:15:49,909 - WARNING - Failed to process OptiA1_18-55-10_2025-09-08_0x43.jpg after retries
2025-09-08 21:15:49,909 - INFO - Attempt 1 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 21:16:10,966 - ERROR - Error during attempt 1 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA732C0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:16:10,966 - INFO - Waiting 10 seconds before retry 2
2025-09-08 21:16:20,967 - INFO - Attempt 2 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 21:16:42,009 - ERROR - Error during attempt 2 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D505D0AA0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:16:42,010 - INFO - Waiting 10 seconds before retry 3
2025-09-08 21:16:52,010 - INFO - Attempt 3 for file: OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 21:17:13,055 - ERROR - Error during attempt 3 for OptiA1_19-16-36_2025-09-08_0x74.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73E00>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:17:13,055 - ERROR - All upload attempts failed for OptiA1_19-16-36_2025-09-08_0x74.jpg
2025-09-08 21:17:13,055 - WARNING - Failed to process OptiA1_19-16-36_2025-09-08_0x74.jpg after retries
2025-09-08 21:17:13,055 - INFO - Upload cycle completed. Waiting 600 seconds
2025-09-08 21:27:13,056 - INFO - Starting new upload cycle
2025-09-08 21:27:13,056 - INFO - Found 0 files in upload log
2025-09-08 21:27:13,057 - INFO - Found 8 image files to process
2025-09-08 21:27:13,057 - INFO - Attempt 1 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 21:27:34,116 - ERROR - Error during attempt 1 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71EE0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:27:34,116 - INFO - Waiting 10 seconds before retry 2
2025-09-08 21:27:44,117 - INFO - Attempt 2 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 21:28:05,156 - ERROR - Error during attempt 2 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71BB0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:28:05,156 - INFO - Waiting 10 seconds before retry 3
2025-09-08 21:28:15,158 - INFO - Attempt 3 for file: OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 21:28:36,216 - ERROR - Error during attempt 3 for OptiA1_17-15-16_2025-09-08_0x78.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA71100>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:28:36,216 - ERROR - All upload attempts failed for OptiA1_17-15-16_2025-09-08_0x78.jpg
2025-09-08 21:28:36,216 - WARNING - Failed to process OptiA1_17-15-16_2025-09-08_0x78.jpg after retries
2025-09-08 21:28:36,217 - INFO - Attempt 1 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 21:28:57,246 - ERROR - Error during attempt 1 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72990>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:28:57,247 - INFO - Waiting 10 seconds before retry 2
2025-09-08 21:29:07,247 - INFO - Attempt 2 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 21:29:28,286 - ERROR - Error during attempt 2 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72FF0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:29:28,286 - INFO - Waiting 10 seconds before retry 3
2025-09-08 21:29:38,287 - INFO - Attempt 3 for file: OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 21:29:59,348 - ERROR - Error during attempt 3 for OptiA1_17-25-20_2025-09-08_0x56.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D505D0110>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:29:59,348 - ERROR - All upload attempts failed for OptiA1_17-25-20_2025-09-08_0x56.jpg
2025-09-08 21:29:59,349 - WARNING - Failed to process OptiA1_17-25-20_2025-09-08_0x56.jpg after retries
2025-09-08 21:29:59,349 - INFO - Attempt 1 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 21:30:20,399 - ERROR - Error during attempt 1 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA0A9F0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:30:20,401 - INFO - Waiting 10 seconds before retry 2
2025-09-08 21:30:30,401 - INFO - Attempt 2 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 21:30:51,434 - ERROR - Error during attempt 2 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA72B10>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:30:51,434 - INFO - Waiting 10 seconds before retry 3
2025-09-08 21:31:01,436 - INFO - Attempt 3 for file: OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 21:31:22,488 - ERROR - Error during attempt 3 for OptiA1_17-27-38_2025-09-08_0x32.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73C20>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:31:22,489 - ERROR - All upload attempts failed for OptiA1_17-27-38_2025-09-08_0x32.jpg
2025-09-08 21:31:22,489 - WARNING - Failed to process OptiA1_17-27-38_2025-09-08_0x32.jpg after retries
2025-09-08 21:31:22,489 - INFO - Attempt 1 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 21:31:43,546 - ERROR - Error during attempt 1 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA73590>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:31:43,546 - INFO - Waiting 10 seconds before retry 2
2025-09-08 21:31:53,547 - INFO - Attempt 2 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
2025-09-08 21:32:14,590 - ERROR - Error during attempt 2 for OptiA1_18-24-58_2025-08-25_0x92.jpg: HTTPSConnectionPool(host='forgevision.ai', port=443): Max retries exceeded with url: /opti/uploadimageapi/upload_image.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029D4FA70DA0>, 'Connection to forgevision.ai timed out. (connect timeout=30)'))
2025-09-08 21:32:14,591 - INFO - Waiting 10 seconds before retry 3
2025-09-08 21:32:24,592 - INFO - Attempt 3 for file: OptiA1_18-24-58_2025-08-25_0x92.jpg
